### ISSUE TITLE
Social share data and image

### ISSUE THREAD

**Issue by sbddesign** [ATLBitLab/twelvecash#40]
Social share data like `og:image`, `description`, `twitter:title`, etc.

**Comment by paulosacramento** [comment]
Hi @sbddesign 
Could you give more details about this issue? I would like to help.

**Comment by sbddesign** [comment]
@paulosacramento Basically, need to ensure that something nice looking is represented when each page of the website is shared to social.

From a design perspective, it means making a 16x9 graphic that will appear when a TC page is rendered to social media.

From a content strategy perspective, it means determining the description text that renders when we share it to social.

From a frontend dev perspective, it means going into the NextJS site and making this happen. (Needs to use the NextJS metadata object if memory serves, I think that is the most current way of handling these things in NextJS land)

**Comment by paulosacramento** [comment]
@sbddesign This is what I have in mind.

**Image**
![TwelveCash](https://github.com/user-attachments/assets/4e760508-8c1a-487f-95f2-c1e6b0538330)

**Title**
Twelve Cash

**Description**
A simple way to share your bitcoin payment info with the world.

Can I improve it somehow?

**Comment by sbddesign** [comment]
Great, thank you. I will add this.

**Comment by sbddesign** [comment]
Thi wil lget merged in #44
